name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
        # cache: maven
    - name: FireFlink suite execution
      run: java -jar fireflink-action-1.0.0.jar ${{vars.FIREFLINK_URL}} ${{vars.FIREFLINK_SUITE_ID}} ${{vars.FIREFLINK_TOKEN}} ${{vars.USERNAME}} ${{vars.FIREFLINK_PROJECT_TYPE}}